/**
 * Domain model representing an inbound Meta webhook event after it has been
 * verified and enriched with tenant context. This is the shape written to the
 * Redis Stream "flow-engine:{tenantId}" and must match
 * contracts/flow-engine-message.schema.json exactly.
 */
export interface MetaMessageItem {
  from: string;
  id: string;
  timestamp: string;
  type:
    | 'text'
    | 'interactive'
    | 'image'
    | 'document'
    | 'audio'
    | 'video'
    | 'sticker'
    | 'location'
    | 'contacts'
    | 'reaction'
    | 'order'
    | 'system'
    | 'unknown';
  text?: { body: string };
  interactive?: Record<string, unknown>;
}

export interface MetaWebhookValue {
  messaging_product: 'whatsapp';
  metadata: {
    display_phone_number?: string;
    phone_number_id: string;
  };
  contacts?: Array<{
    profile?: { name?: string };
    wa_id?: string;
  }>;
  messages?: MetaMessageItem[];
  statuses?: Array<Record<string, unknown>>;
}

export interface WebhookEnvelope {
  /** UUIDv4 generated by gateway at ingestion time. Used as idempotency key. */
  message_id: string;
  /** ISO 8601 timestamp at which the gateway received the webhook. */
  received_at: string;
  /** Tenant UUID resolved from phone_number_id. */
  tenant_id: string;
  /** Meta phone number ID from webhook metadata. */
  phone_number_id: string;
  /** Full Meta Cloud API value object preserved verbatim for auditability. */
  raw: MetaWebhookValue;
}
